source 'https://cdn.cocoapods.org/'
source 'https://pt.singsound.com:10081/singsound-public/SingSoundSDKCocoaPodRepo.git'
use_frameworks!

platform :ios, '8.0'

target 'YJTaskMark_Example' do
  pod 'YJTaskMark', :path => '../'

end
